//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class BindSearchItem
    {
        public long ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string CategoryName { get; set; }
        public string UomName { get; set; }
        public Nullable<int> QtyPack { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UnitPriceCurrency { get; set; }
        public Nullable<long> UnitPricevalue { get; set; }
        public Nullable<decimal> EachPrice { get; set; }
        public string NDC { get; set; }
        public Nullable<bool> Standard { get; set; }
        public Nullable<bool> NonStandard { get; set; }
        public string GPBillingCode { get; set; }
        public string ItemName { get; set; }
    }
}
