//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class BindVendorItemMapReport
    {
        public string CategoryName { get; set; }
        public Nullable<long> ItemID { get; set; }
        public string VendorItemID { get; set; }
        public string ItemDescriptionWithCode { get; set; }
        public string VendorDescriptionWithCode { get; set; }
        public long ItemMapID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public string VendorDescription { get; set; }
        public string ItemDescription { get; set; }
        public string IsActive { get; set; }
        public string LoggedBy { get; set; }
    }
}
