//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class BindITRequestPOReport
    {
        public Nullable<long> ITRequestMasterID { get; set; }
        public Nullable<long> ITRequestDetailID { get; set; }
        public Nullable<long> CorporateID { get; set; }
        public Nullable<long> Facility { get; set; }
        public Nullable<long> VendorID { get; set; }
        public string CorporateName { get; set; }
        public string FacilityDescription { get; set; }
        public string VendorDescription { get; set; }
        public string ITRNo { get; set; }
        public string ITNNo { get; set; }
        public string Status { get; set; }
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Remarks { get; set; }
        public string Audit { get; set; }
        public string EquipmentSubCategoryDescription { get; set; }
        public string EquipmentListDescription { get; set; }
        public string SerialNo { get; set; }
        public string User { get; set; }
        public Nullable<decimal> PriceperUnit { get; set; }
        public Nullable<int> Orderquantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Reason { get; set; }
        public string Orderremarks { get; set; }
        public string Requesttype { get; set; }
        public string Shipping { get; set; }
        public string RequestDate { get; set; }
        public string Shippingcost { get; set; }
        public string Tax { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string LoggedinBy { get; set; }
    }
}
