//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class BindCapitalItemRequestReport
    {
        public string CorporateName { get; set; }
        public string FacilityDescription { get; set; }
        public string VendorDescription { get; set; }
        public string Shipping { get; set; }
        public string Type { get; set; }
        public string Tax { get; set; }
        public string ShippingCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string Requestdate { get; set; }
        public string CRNo { get; set; }
        public string SerialNo { get; set; }
        public Nullable<long> OrderQuantity { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string EquipmentSubCategoryDescription { get; set; }
        public string EquipmentListDescription { get; set; }
        public string Reason { get; set; }
        public Nullable<long> CapitalItemMasterID { get; set; }
        public Nullable<long> CapitalItemDetailsID { get; set; }
        public string LoggedBy { get; set; }
    }
}
