//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class BindTransferOutReport
    {
        public long TransferOutID { get; set; }
        public string TransferNo { get; set; }
        public string TransferDate { get; set; }
        public Nullable<long> Transferqty { get; set; }
        public Nullable<long> QtyPack { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string CorporateDescription { get; set; }
        public string TransferFrom { get; set; }
        public string TransferTo { get; set; }
        public string ItemDescription { get; set; }
        public long ItemID { get; set; }
        public string CategoryName { get; set; }
        public string UomName { get; set; }
        public string LoggedBy { get; set; }
    }
}
