//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class BindITNNOvalues
    {
        public string EquipmentList { get; set; }
        public string SerialNo { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<long> ITRequestMasterID { get; set; }
        public long EquipementSubCategoryID { get; set; }
        public Nullable<long> EquipementListID { get; set; }
        public long ITReceivingMasterID { get; set; }
        public long ITReceivingDetailsID { get; set; }
        public string EquimentSubCategory { get; set; }
        public Nullable<decimal> PricePerQty { get; set; }
        public Nullable<int> BalanceQty { get; set; }
        public string PackingSlipNo { get; set; }
        public Nullable<System.DateTime> PackingDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Reason { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> ReceivingQty { get; set; }
        public string ReceivingAction { get; set; }
        public string OtherReason { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public string ShippingCost { get; set; }
        public string Tax { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string User { get; set; }
        public string ITNNo { get; set; }
        public Nullable<long> RequestITOrderID { get; set; }
    }
}
