//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class GetCROrderContentPO
    {
        public string FacilityDescription { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPhone { get; set; }
        public string BillFax { get; set; }
        public string VendorDescription { get; set; }
        public string VendorAddress { get; set; }
        public string VendorAddress2 { get; set; }
        public string VendorCity { get; set; }
        public string VendorState { get; set; }
        public string VendorPhone { get; set; }
        public string VendorFax { get; set; }
        public string PoEmail { get; set; }
        public string CRNo { get; set; }
        public string CRONo { get; set; }
        public string OrderDate { get; set; }
        public string RequestType { get; set; }
        public Nullable<long> EquipmentSubCategory { get; set; }
        public Nullable<long> EquipmentList { get; set; }
        public Nullable<long> OrderQuantity { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public string SerialNo { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public long CapitalItemMasterID { get; set; }
        public string CorporateName { get; set; }
        public string EquipmentSubCategoryDescription { get; set; }
        public string EquipmentListDescription { get; set; }
        public string OrderBy { get; set; }
        public string ShipAccount { get; set; }
        public string Shipping { get; set; }
        public string UserEmail { get; set; }
        public string UserPhoneNo { get; set; }
        public string Faczipcode { get; set; }
        public string BillZipCode { get; set; }
        public string VendorZip { get; set; }
        public string BillAccount { get; set; }
        public string ShippingCost { get; set; }
        public string Tax { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string Status { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public byte[] OrderContent { get; set; }
        public Nullable<long> CorporateID { get; set; }
        public Nullable<long> FacilityID { get; set; }
        public string FacPhone { get; set; }
        public string FacFax { get; set; }
        public string CorporateDescription { get; set; }
        public string ShipAD { get; set; }
        public string BillAD { get; set; }
        public string VendorAD { get; set; }
        public string LoggedBy { get; set; }
    }
}
