//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class GetReceivedQtyInfo
    {
        public long ItemID { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string PRONo { get; set; }
        public string VendorDescription { get; set; }
        public string VendorItemID { get; set; }
        public string UomName { get; set; }
        public Nullable<long> QtyPack { get; set; }
        public Nullable<int> ReceivedQty { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
