//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class GetServiceRequestPoReportDetails
    {
        public long ServiceRequestMasterID { get; set; }
        public Nullable<long> ServiceRequestDetailsID { get; set; }
        public string CorporateName { get; set; }
        public string FacilityDescription { get; set; }
        public string VendorDescription { get; set; }
        public string SRNo { get; set; }
        public string SPONo { get; set; }
        public string Status { get; set; }
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string PoRemarks { get; set; }
        public string Audit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Service { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> DetailsCreatedOn { get; set; }
        public string ServiceType { get; set; }
        public string Equipcategory { get; set; }
        public string EquipSubcategory { get; set; }
        public string EquList { get; set; }
        public string LoggedinBy { get; set; }
    }
}
