//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class GetServiceRequestPOGenerateDetails
    {
        public long ServiceRequestMasterID { get; set; }
        public Nullable<long> ServiceRequestDetailsID { get; set; }
        public Nullable<long> CorporateID { get; set; }
        public string CorporateName { get; set; }
        public Nullable<long> FacilityID { get; set; }
        public string FacilityDescription { get; set; }
        public string FacilityShortName { get; set; }
        public Nullable<long> VendorID { get; set; }
        public string VendorDescription { get; set; }
        public string VendorShortName { get; set; }
        public string SRNo { get; set; }
        public string SRPONO { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Action { get; set; }
        public string OrdRemarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string Audit { get; set; }
        public byte[] Ordercontent { get; set; }
        public string CorporateDescription { get; set; }
    }
}
