//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class GetUserPagePermission
    {
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsViewOnly { get; set; }
        public Nullable<long> MainMenuID { get; set; }
        public Nullable<long> SubMenuID { get; set; }
        public Nullable<bool> IsEmailNotification { get; set; }
    }
}
