//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITReceivingMaster
    {
        public long ITReceivingMasterID { get; set; }
        public Nullable<long> ITRequestMasterID { get; set; }
        public string ITRONo { get; set; }
        public string PackingSlipNo { get; set; }
        public Nullable<System.DateTime> PackingDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string ReceivingAction { get; set; }
        public string Reason { get; set; }
        public string OtherReason { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FinalStatus { get; set; }
        public Nullable<long> ReceivingOrder { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<long> LastModifiedBy { get; set; }
        public string InvoiceStatus { get; set; }
        public Nullable<long> InvoicedBy { get; set; }
        public Nullable<long> PartialBy { get; set; }
        public Nullable<System.DateTime> PartialOn { get; set; }
        public Nullable<long> VoidBy { get; set; }
        public Nullable<System.DateTime> VoidOn { get; set; }
        public Nullable<long> ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public string ShippingCost { get; set; }
        public string Tax { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string ITNNo { get; set; }
        public Nullable<long> RequestITOrderID { get; set; }
    }
}
