//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machinemaster
    {
        public long MachineID { get; set; }
        public Nullable<long> FacilityID { get; set; }
        public string Manufacturer { get; set; }
        public string Manufacturedyear { get; set; }
        public Nullable<int> Hoursonthemachine { get; set; }
        public Nullable<long> EquipmentCategory { get; set; }
        public Nullable<long> EquipementList { get; set; }
        public string Model { get; set; }
        public string SerialNo { get; set; }
        public string Warranty { get; set; }
        public string GpAccountCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<long> LastModifiedBy { get; set; }
        public Nullable<long> EquipementSubcategory { get; set; }
        public Nullable<long> EquipmentList_temp { get; set; }
    
        public virtual Facility Facility { get; set; }
    }
}
