//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventroy.Service
{
    using System;
    
    public partial class SearchServiceRequestPurchaseOrderDetails
    {
        public Nullable<long> ServiceRequestMasterID { get; set; }
        public Nullable<long> ServiceRequestDetailsID { get; set; }
        public Nullable<long> VendorID { get; set; }
        public string VendorName { get; set; }
        public string Service { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Unit { get; set; }
        public string Audit { get; set; }
        public string Action { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
